config/routes.rb
Rails.application.routes.draw do

  root "posts#index"

  get "/home" => "home#home"
  get "/about" => "home#about"

  resources :users

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end

  resources :posts do
    resources :votes, only: [:create, :destroy, :update]
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    can :manage, Post do |p|
      user == p.user
    end

    can :manage, Comment do |c|
      user == c.user
    end

    can :destroy, Comment do |c|
      user == c.post.user
    end

    can :manage, User do |u|
      user == u.user
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post

  belongs_to :user

  validates :body, presence: true

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/like.rb
class Like < ActiveRecord::Base
  
  validates :post_id, uniqueness: {scope: :user_id}

  belongs_to :user
  belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates(:title, {presence:   true,
                    uniqueness: {message: "was used already"},
                    length:     {minimum: 3}})

  validates :body, presence:   true,
                   uniqueness: {scope: :title}

  has_many :comments, dependent: :destroy

  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  has_many :votes, dependent: :destroy
  has_many :voting_users, through: :votes, source: :user

  mount_uploader :image, ImageUploader

  extend FriendlyId
  friendly_id :title, use: :slugged


  def liked_by?(user)
    like_for(user).present?
  end

  def like_for(user)
    likes.find_by_user_id(user.id)
  end

  def voted_on_by?(user)
    vote_for(user).present?
  end

  def vote_for(user)
    votes.find_by_user_id(user.id)
  end

  def vote_result
    votes.select { |v| v.is_up? }.count - votes.select { |v| !v.is_up? }.count
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tagging, dependent: :destroy
  has_many :posts, through: :taggings

  validates :name, presence: true, uniqueness: true 
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password


  has_many :posts, dependent: :destroy

  has_many :comments, dependent: :destroy

  validates :email, presence: true, uniqueness: true

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :votes, dependent: :nullify
  has_many :voted_posts, through: :votes, source: :post

  mount_uploader :image, ImageUploader

  # extend FriendlyId
  # friendly_id :full_name, use: :slugged

  def full_name
    "#{first_name} #{last_name}".strip
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :post_id, uniqueness: {scope: :user_id}
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home

  end

  def about

  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user

  def create
    @like = Like.new
    @post = Post.friendly.find params[:post_id]
    @like.post = @post
    @like.user = current_user
    respond_to do |format|
      if current_user != @post.user
        @like.save
        # LikesMailer.notify_post_owner(like).deliver_now
        format.html {redirect_to post_path(post)}
        format.js {render :create_success}
      else
        format.html {redirect_to post_path(post), alert: "you can't like your on post"}
        format.js {render js: "alert(you can't like your on post);"}
      end
    end
  end

  def destroy
    @post = Post.friendly.find params[:post_id]
    @like = current_user.likes.find params[:id]
    @like.destroy
      respond_to do |format|
        format.html {redirect_to post_path(post)}
        format.js { render }
      end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user, except: [:index, :show]

  before_action :find_post, only: [:show, :edit, :update, :destroy]

  before_action :authorize, only: [:edit, :update, :destroy]


  def index
    @posts = Post.all.order(:created_at).reverse_order
  end

  def show
    @comments = @post.comments
    @comment = Comment.new(post: @post)
  end


  def new
    @post = Post.new
  end


  def edit
    redirect_to root_path, alert: "Access denied." unless can? :edit, @post
  end


  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to(post_path(@post), notice: "Post Created!")
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render "edit"
    end
  end

  def destroy
  @post.destroy
  redirect_to posts_path
end


  private

  def post_params
    params.require(:post).permit([:title, :body, {tag_ids: []}], :image)
  end

  def authorize
    redirect_to root_path, alert: "Access denied!" unless can? :manage, @post
  end

  def find_post
    # finding the question by its id
    @post = Post.friendly.find params[:id]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
      if @user.save
        #UsersMailer.notify_new_user(User.last).deliver_now
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render :new
      end
  end

  def show
    @user = User.find params[:id]
    @posts = @user.posts
    # .friendly
  end

  def edit
    #redirect_to root_path, alert: "Access denied." unless can? :edit, @user
    @user = current_user
  end

  def update
    @user = User.find params[:id]
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render "edit"
    end
  end


  private


  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,
                                              :password, :password_confirmation, :image)
  end


end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user

  def create
    post = Post.friendly.find params[:post_id]
    vote = current_user.votes.new vote_params
    vote.post = post
    if vote.save
      redirect_to post_path(post)
    else
      redirect_to post_path(post)
    end
  end

  def destroy
    post = Post.friendly.find params[:post_id]
    vote = current_user.votes.find params[:id]
    vote.destroy
    redirect_to post_path(post)
  end

  def update
    vote = current_user.votes.find params[:id]
    post = Post.friendly.find params[:post_id]
    if vote.update vote_params
      redirect_to post_path(post)
    else
      redirect_to post_path(post)
    end
  end

  private

  def vote_params
    params.require(:vote).permit(:is_up)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? && @post.liked_by?(current_user)%>
  <%= link_to fa_icon("heart"), post_like_path(@post, @post.like_for(current_user)),
                method: :delete, class: "if icon-heart text-danger", remote: true %>
<% else %>
  <%= link_to fa_icon("heart-o"), post_likes_path(@post),
                method: :post, class: "else icon-heart text-danger", remote: true %>
<% end %>
  <%= @post.likes.count %> 

app/views/likes/create_success.js.erb
$("#like").html("<%= j render '/likes/like', like: @like %>")

app/views/likes/destroy.js.erb
$("#like").html("<%= j render '/likes/like', like: @like %>")

app/views/posts/_form.html.erb
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
<%= form_for @post do |f| %>

  <div class="form-group">
    <%= f.label :title, "Title"  %>
    <%= f.text_field :title, class: "form-control"%>
  </div>


  <div class="form-group">
    <%= f.label :body, "Your story..." %>
    <%= f.text_area :body, class: "form-control", rows: "7" %>
  </div>

  <div class="form-group">
    <%= f.collection_check_boxes :tag_ids, Tag.order(:name), :id, :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= f.submit "Post your story ", class: "btn btn-primary btn-md btn-block" %>
  </div>

  <% end %>

    </div>
    <div class="col-md-3"></div>
</div>

app/views/posts/edit.html.erb
<h2 class="text-center">Edit your post</h2>


<%= render "form" %>

app/views/posts/index.html.erb
<table>
  <% @posts.each do |post| %>

    <tr>
      <td>
        <h1><%= link_to post.title, post_path(post) %></h1>

        <% if post.user %>
          <p class="text-left">
            <%= link_to (image_tag post.user.image.url(:thumb), class: "img-circle"), user_path(post.user.id) %>
            <%= link_to post.user.full_name, user_path(post.user.id)%>
            <%= "@" + post.user.created_at.strftime(" %b %d, %Y")  %>
          </p>
        <% end %>

        <% if post.image.present? %>
          <%= link_to (image_tag post.image.url(:post_size)), post_path(post)%>
        <% end %>
        <p class="texto"><%= post.body.truncate(200)%></p>
        <p><%= link_to "Read more...", post_path(post) %></p>
        <hr/>
      </td>
    </tr>

  <% end %>
</table>

app/views/posts/new.html.erb
<h2 class="text-center">Create your post</h2>


<%= render "form" %>

app/views/posts/show.html.erb
<!-- titulo do post -->

<h2><%= @post.title %></h2>

<!-- created by -->
<% if @post.user %>
  <p class="text-left">
  <%= image_tag @post.user.image.url(:thumb), class: "img-circle" %>
  <%= link_to @post.user.full_name, user_path(@post.user.id) %>
  <%= "@" + @post.user.created_at.strftime(" %b %d, %Y")  %>
</p>
<% end %>

<!-- image -->
<% if @post.image.present? %>
  <%= image_tag @post.image.url(:post_size) %>
<% end %>


<!-- edit delete -->
<p class="text-right">
  <% if can? :edit, @post %>
    <%= link_to fa_icon("pencil-square-o"), edit_post_path(@post), class: "icon-comm-destroy" %>
  <% end %>

  <% if can? :destroy, @post %>
    <%= link_to fa_icon("trash"), post_path(@post), method: :delete, class: "icon-comm-destroy",
            data: { confirm: 'Má oooee, Você está certo dissoammm? ' } %>
  <%end%>
</p>

<!-- body -->
<p class="texto"><%= @post.body %></p>

<!-- tags -->
<% if @post.tags.any? %>
  <% @post.tags.each do |tag| %>
<p class="label label-info"><%= tag.name %></p>
  <% end %>
<% end %>

<!-- vote button -->
<div class="text-right">

  votes: <%= @post.vote_result %>
  
  <% if !user_signed_in? || !@post.voted_on_by?(current_user) %>
    <%= link_to fa_icon("arrow-circle-up"), post_votes_path(@post,
    {vote: {is_up: true}}), method: :post, class: "icon-vote-green text-success"%>
    <%= link_to fa_icon("arrow-circle-down"), post_votes_path(@post,
    {vote: {is_up: false}}), method: :post, class: "icon-vote-red text-danger"%>

  <% elsif @post.vote_for(current_user).is_up? %>
    <%= link_to fa_icon("arrow-circle-up"), post_vote_path(@post, @post.vote_for(current_user)),
    method: :delete, class: "icon-vote-green text-success" %>
    <%= link_to fa_icon("arrow-circle-down"), post_vote_path(@post, @post.vote_for(current_user),
    vote: {is_up: false}), method: :delete, class: "icon-vote-red text-danger"%>

  <% elsif !@post.vote_for(current_user).is_up?%>
    <%= link_to fa_icon("arrow-circle-up"), post_vote_path(@post, @post.vote_for(current_user),
    vote: {is_up: true}), method: :patch, class: "icon-vote-green text-success"%>
    <%= link_to fa_icon("arrow-circle-down"), post_vote_path(@post, @post.vote_for(current_user)),
    method: :delete, class: "icon-vote-red text-danger"%>

  <% end %>

</div>

<!-- like button  -->

  <div class="text-right" id="like">
      <%= render 'likes/like' %>
  </div>




<!-- create comment -->
<div class="form-group">
  <%= form_for [@post, @comment], remote: true do |f| %>
    <%= f.label :body, "Write a comment" %>
    <%= f.text_area :body, class: "form-control", rows: "3" %>
    <br>
    <%= f.submit "Comment", class: "btn btn-primary btn-md btn-block", data: {disable_with: "Saving..."}  %>
  <% end %>
</div>

<!-- comments -->
<div id="comment">
  <% @post.comments.each do |comment| %>
    <%= render "/comments/comment", comment: comment %>
  <% end %>
</div>


<div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>

app/views/users/_form.html.erb
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :first_name, "what your name?" %>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, "and last name?" %>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email, "what your email?"%>
      <%= f.email_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password, "create a password"%>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, "repete the password" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.file_field :image, class: "form-control" %>
    </div>
    <%= f.submit "create user", class: "btn btn-primary btn-sm btn-block" %>
  <% end %>
    </div>
    <div class="col-md-3"></div>
</div>

app/views/users/edit.html.erb
<h2><p class="text-center">Edit</p></h2>

<%= render "form" %>

app/views/users/new.html.erb
<h2><p class="text-center">Sign up</p></h2>

<%= render "form" %>

app/views/users/show.html.erb
<br>
<div class="text-center">
  <% if @user.image.present? %>
  <%= image_tag @user.image.url(:medium), class: "img-circle" %>
  <% end %>
</div>
<h3 class="text-center"> <%= @user.full_name %> </h3>

<% if @user == current_user %>
<p class="text-center"><%= link_to "Edit profile", edit_user_path %></p>
<% end %>


<table>
  <% @posts.each do |post| %>

    <tr>
      <td>
        <h1><%= link_to post.title, post_path(post) %></h1>

        <% if post.user %>
          <p class="text-left">
            <%= link_to (image_tag post.user.image.url(:thumb), class: "img-circle"), user_path(post.user.id) %>
            <%= link_to post.user.full_name, user_path(post.user.id)%>
            <%= "@" + post.user.created_at.strftime(" %b %d, %Y")  %>
          </p>
        <% end %>

        <% if post.image.present? %>
          <%= link_to (image_tag post.image.url(:post_size)), post_path(post)%>
        <% end %>
        <p class="texto"><%= post.body.truncate(150) %></p>
        <hr/>
      </td>
    </tr>

  <% end %>
</table>