config/routes.rb
Rails.application.routes.draw do

  root "posts#index"

  get "/home" => "home#home"
  get "/about" => "home#about"

  resources :users

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end

  resources :posts do
    resources :votes, only: [:create, :destroy, :update]
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    can :manage, Post do |p|
      user == p.user
    end

    can :manage, Comment do |c|
      user == c.user
    end

    can :destroy, Comment do |c|
      user == c.post.user
    end

    can :manage, User do |u|
      user == u.user
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post

  belongs_to :user

  validates :body, presence: true

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/like.rb
class Like < ActiveRecord::Base
  
  validates :post_id, uniqueness: {scope: :user_id}

  belongs_to :user
  belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates(:title, {presence:   true,
                    uniqueness: {message: "was used already"},
                    length:     {minimum: 3}})

  validates :body, presence:   true,
                   uniqueness: {scope: :title}

  has_many :comments, dependent: :destroy

  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  has_many :votes, dependent: :destroy
  has_many :voting_users, through: :votes, source: :user

  mount_uploader :image, ImageUploader

  extend FriendlyId
  friendly_id :title, use: :slugged


  def liked_by?(user)
    like_for(user).present?
  end

  def like_for(user)
    likes.find_by_user_id(user.id)
  end

  def voted_on_by?(user)
    vote_for(user).present?
  end

  def vote_for(user)
    votes.find_by_user_id(user.id)
  end

  def vote_result
    votes.select { |v| v.is_up? }.count - votes.select { |v| !v.is_up? }.count
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tagging, dependent: :destroy
  has_many :posts, through: :taggings

  validates :name, presence: true, uniqueness: true 
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password


  has_many :posts, dependent: :destroy

  has_many :comments, dependent: :destroy

  validates :email, presence: true, uniqueness: true

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :votes, dependent: :nullify
  has_many :voted_posts, through: :votes, source: :post

  mount_uploader :image, ImageUploader

  # extend FriendlyId
  # friendly_id :full_name, use: :slugged

  def full_name
    "#{first_name} #{last_name}".strip
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :post_id, uniqueness: {scope: :user_id}
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home

  end

  def about

  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user

  def create
    @like = Like.new
    @post = Post.friendly.find params[:post_id]
    @like.post = @post
    @like.user = current_user
    respond_to do |format|
      if current_user != @post.user
        @like.save
        # LikesMailer.notify_post_owner(like).deliver_now
        format.html {redirect_to post_path(post)}
        format.js {render :create_success}
      else
        format.html {redirect_to post_path(post), alert: "you can't like your on post"}
        format.js {render js: "alert(you can't like your on post);"}
      end
    end
  end

  def destroy
    @post = Post.friendly.find params[:post_id]
    @like = current_user.likes.find params[:id]
    @like.destroy
      respond_to do |format|
        format.html {redirect_to post_path(post)}
        format.js { render }
      end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_flash_messages.html.erb
<br>

<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="nav navbar-default">
  <div class="container-fluid">


    <a class="navbar-brand" href="/">
      <%= image_tag "logo.png" %>
    </a>




  <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <form class="navbar-form navbar-right" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form> -->



<div class="nav navbar-nav navbar-right">
  <li><%= link_to "Posts", posts_path %></li>
  <li><%= link_to "Add Post", new_post_path %></li>

  <% if user_signed_in? %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
     aria-haspopup="true" aria-expanded="false">
     <%#= current_user.full_name %>
     <%= image_tag current_user.image.url(:thumb), class: "img-circle" %>
     <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to "Profile", user_path(current_user) %></li>
      <li><%= link_to "Logout", sessions_path, method: :delete%></li>
    </ul>
  </li>

  <% else %>

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Enter <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to "Sign up", new_user_path %></li>
      <li><%= link_to "Login", new_session_path %></li>
    </ul>
  </li>

  <% end %>
</div>
  <!-- </div> -->

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous"> -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300|Lora' rel='stylesheet' type='text/css'>
</head>
<body>

<%= render "/layouts/nav" %>


<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">


      <%= render "/layouts/flash_messages" %>
      <%= yield %>


    </div>
    <div class="col-md-2"></div>
</div>


</body>
</html>